# fly.toml file generated for m1craft-server on 2022-07-04T11:07:17-04:00

app = "m1craft-server"

[env]

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
